# Generated by Django 5.1 on 2024-09-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_producto_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto_carrito',
        ),
    ]
