# Generated by Django 5.1 on 2024-09-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
