# Generated by Django 5.1 on 2024-09-11 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_mensajecontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
