# Generated by Django 5.1 on 2024-09-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
